<?php

/**
 * BaseArtist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Songs
 * @property Doctrine_Collection $ArtistSong
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getSongs()      Returns the current record's "Songs" collection
 * @method Doctrine_Collection getArtistSong() Returns the current record's "ArtistSong" collection
 * @method Artist              setId()         Sets the current record's "id" value
 * @method Artist              setName()       Sets the current record's "name" value
 * @method Artist              setSongs()      Sets the current record's "Songs" collection
 * @method Artist              setArtistSong() Sets the current record's "ArtistSong" collection
 * 
 * @package    Blues
 * @subpackage model
 * @author     Włodzimierz Gajda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artist');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));

        $this->option('orderBy', 'name');
        $this->option('collate', 'utf8_polish_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Song as Songs', array(
             'refClass' => 'ArtistSong',
             'local' => 'artist_id',
             'foreign' => 'song_id'));

        $this->hasMany('ArtistSong', array(
             'local' => 'id',
             'foreign' => 'artist_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => false,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}