<?php

/**
 * BaseArtistSong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $artist_id
 * @property integer $song_id
 * @property Artist $Artist
 * @property Song $Song
 * 
 * @method integer    getArtistId()  Returns the current record's "artist_id" value
 * @method integer    getSongId()    Returns the current record's "song_id" value
 * @method Artist     getArtist()    Returns the current record's "Artist" value
 * @method Song       getSong()      Returns the current record's "Song" value
 * @method ArtistSong setArtistId()  Sets the current record's "artist_id" value
 * @method ArtistSong setSongId()    Sets the current record's "song_id" value
 * @method ArtistSong setArtist()    Sets the current record's "Artist" value
 * @method ArtistSong setSong()      Sets the current record's "Song" value
 * 
 * @package    Blues
 * @subpackage model
 * @author     Włodzimierz Gajda
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtistSong extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artist_has_song');
        $this->hasColumn('artist_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('song_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artist', array(
             'local' => 'artist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Song', array(
             'local' => 'song_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}