prod:
  frontend_base_url:  http://blues.gajdaw.pl
  backend_base_url:   http://admin.blues.gajdaw.pl

staging:
  frontend_base_url:  http://blues.gajdaw.pl
  backend_base_url:   http://admin.blues.gajdaw.pl

dev:
  frontend_base_url:  http://blues.gajdaw.pl.localhost
  backend_base_url:   http://admin.blues.gajdaw.pl.localhost

