<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addartisthassong extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('artist_has_song', array(
             'artist_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'song_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'artist_id',
              1 => 'song_id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('artist_has_song');
    }
}