<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('artist', 'email');
    }

    public function down()
    {
        $this->addColumn('artist', 'email', 'string', '128', array(
             ));
    }
}