<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsong extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('song', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'lyrics' => 
             array(
              'type' => 'string',
              'length' => 4096,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
              'song_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('song');
    }
}